### ISSUE TITLE
Refactor thumbnails in File struct

### ISSUE THREAD

**Issue by kiyoto** [slack-rs/slack-rs-api#23]
Currently, thumbnail-related fields of `File` struct are `Option<String>`. This design can be improved because the triple (`thumb_N`, `thumb_N_w`, `thumb_N_h`) should all exist or all absent for `N` = 360, 480, 720, 960 and 1024.

**Comment by mthjones** [comment]
I think this will require some thought about what this library represents. In its current state, it could be entirely machine generated if we had a schema to work off of. Making a change like this would move the library away from being a direct mapper.

Now, that's not to say I don't _want_ to provide helpers to make the data model easier to manage (e.g. builder for messages & attachments, the above mentioned Thumbnail, etc). I just wonder if we should leave the existing implementation as-is so that it _could_ be machine-generated in the future and provide nicer abstractions in another module/crate instead.

**Comment by kiyoto** [comment]
👍 for exploring machine-generated/macro-based approach.

**Comment by BenTheElder** [comment]
Noting here that while machine-generated types would be interesting, I think for now we should probably stick to types that match the slack [docs](https://api.slack.com/types/file) as best as possible (particularly since optional fields need to be marked by hand after reading the slack docs).
 We may revisit this in the future but for now I'm going to close this since as awkward as it might be having so many optional fields, we do match the documented structure in doing so.
