### ISSUE TITLE
Add support for slackbot_response and thread_broadcast Messages

### ISSUE THREAD

**Issue by saethlin** [slack-rs/slack-rs-api#55]
I'm working on a patch for this, does anyone else have something?

**Comment by dten** [comment]
i don't have anything

**Comment by saethlin** [comment]
I have additions for these and bot_add + bot_remove at the ready, I'll send them as soon as #56 gets merged/approved.

Sidenote: It looks like the `id` field may be inconsistently-typed as well, but I don't have enough message volume to be sure.

**Comment by saethlin** [comment]
@mthjones Did a bunch of work a while back on codegen that looks like it might exist to solve this, should it?

Unfortunately it looks like the codegen tool is broken, and this project seems rather abandoned? I don't mean to be rude, but this project really needs some TLC. Is it really a good idea (in such a state) to depend on a project written in NodeJS?

**Comment by mthjones** [comment]
> Unfortunately it looks like the codegen tool is broken
Probably. It was hacked together before Slack had any sort of standard for their API, so the best it could do was scrape the web pages and try to generate a schema from that. Slack had no consistent API structure or versioning, so it was impossible to maintain. Looks like [there's an actual schema now](https://github.com/slack-rs/slack-rs-api/issues/53), so that sounds like it'd be a great starting point to improve this library and remove the NodeJS dev dependency!

**Comment by dten** [comment]
these types exist now since v0.23
