### ISSUE TITLE
Willing to accept PRs?

### ISSUE THREAD

**Issue by leshow** [slack-rs/slack-rs-api#86]
I'd like to use this library and some parts of it. On a cursory skim I see some code that can be eliminated and replaced with some of serde's proc macro attribute options. I'd also like to provide an async client. Would you be open to upstreaming these changes ?

**Comment by dten** [comment]
Hey yes of course, that would be much appreciated.

I've been thinking about async in this crate and in the rtm crate, since the landscape looks reasonable stable, but haven't had any time to put into them.

I was planning on merging the timestamp PR soon, I've been using it for a while now and everything had been fine. Probably want those changes in before doing anything huge.

**Comment by leshow** [comment]
Cool! Since you're already using `reqwest` switching to async is actually not that bad. I was mostly able to do it with find and replace.
